Repository jupyterlab-contrib/jupyterlab-link-share, pull requests merged in 2021-11, with the labels that each got.

#21 Use default user token when running under JupyterHub
  src/index.ts
Labels: bug

#22 Automated Changelog Entry for 0.2.2 on main
  CHANGELOG.md
Labels: documentation

#24 Add a rudimentary warning to the link share dialog
  src/index.ts
Labels: enhancement

#26 Automated Changelog Entry for 0.2.3 on main
  CHANGELOG.md
Labels: documentation

#27 Show correct URL when using retrolab
  package.json
  src/index.ts
  yarn.lock
Labels: enhancement

#29 Automated Changelog Entry for 0.2.4 on main
  CHANGELOG.md
Labels: documentation

#30 Add Binder files to be able to try with RetroLab
  .binder/environment.yml
  .binder/postBuild
Labels: maintenance

#31 Add .binder to the check manifest ignore list
  pyproject.toml
Labels: maintenance

#32 Turn on collaborative mode on Binder
  jupyter_config.json
Labels: maintenance
